### ISSUE TITLE
[bug] The callout insertion feature of the plugin does not work under my Obsidian.

### ISSUE THREAD

**Issue by alexinea** [edonyzpc/personal-assistant#144] opened 2023-07-07 03:30 UTC
**Describe the bug**
The callout insertion feature of the plugin does not work under my Obsidian.

Nothing happened.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

**Comment by edonyzpc** [comment] 2023-07-07 03:35
Thank you for reporting. 
Did you install the plugin named "Callout Manager" which is the dependency of running callout insertion?
<img width="477" alt="image" src="https://github.com/edonyzpc/personal-assistant/assets/7744664/a506eb2f-8d04-4c2f-ae99-df278748b52a">

**Comment by alexinea** [comment] 2023-07-08 05:33
Yes, I have installed and enabled the "Callout Manager" plugin.

**Comment by edonyzpc** [comment] 2023-07-09 06:47
I have no Windows testing environment and cannot reproduce it. So can you provide debug info from obsidian show debug info command.

**Comment by Mansarde** [comment] 2023-07-22 21:28
This stumped be too at first, but after watching the demonstration GIF (especially what keys are used), I noticed how the feature works:

After choosing a callout from the list (i.e. after pressing ENTER), its code is in the clipboard and you have to ***paste*** it (CTRL+V) into the note!

**Comment by edonyzpc** [comment] 2023-07-23 07:20
> This stumped be too at first, but after watching the demonstration GIF (especially what keys are used), I noticed how the feature works:
> 
> After choosing a callout from the list (i.e. after pressing ENTER), its code is in the clipboard and you have to _**paste**_ it (CTRL+V) into the note!

Thank you for your response.
And yes, the `list-callout` command is designed as selecting from a list and pasting from the clipboard. I will update the document for users and try to find a better UX, especially on mobile devices.

**Comment by Enteleform** [comment] 2023-11-11 19:03
@edonyzpc

Just ran into the same issue as Mansarde, I also expected it to insert the callout at the active view's cursor.

Any chance you could add a setting or separate command for the insertion functionality?

**Comment by edonyzpc** [comment] 2023-11-12 09:42
@Enteleform Hi there, Thank you for your comment.

It's not a bug. Now this plugin will copy the callout content into the clipboard when selected. You just need `CMD + V` to paste it into the place you want to insert.

I will add the feature to paste it into the cursor position when the listed callout is selected. Please check the next new version which will be released in the next week.

**Comment by Enteleform** [comment] 2023-11-12 16:06
@edonyzpc &nbsp; Excellent! Thank you for adding this 🙏

**Comment by edonyzpc** [comment] 2023-11-16 14:37
close with PR https://github.com/edonyzpc/personal-assistant/pull/216 and check the latest release version.

**Closed by edonyzpc** 2023-11-16 14:37 UTC
Labels: bug
